
---
spring:
  jpa:
    generate-ddl: true
  cloud:
    services:
      registrationMethod: route
      
management:
    security:
        enabled: false
        
security:
  basic:
    enabled: false